name: PHPStan

on:
  pull_request:
    branches: ["staging"]
    paths:
      - "**.php"
      - "phpstan.neon.dist"
      - ".github/workflows/phpstan.yml"

permissions:
  contents: write

jobs:
  phpstan:
    uses: ITinternalDiMartino/ci-workflows/.github/workflows/phpstan.yml@main
    with:
      php-version: "8.4"
      phpstan-config: "phpstan.neon.dist"
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
