name: run tests

on:
  pull_request:
    branches: ["staging"]
    paths:
      - "**.php"
      - ".github/workflows/run-tests.yml"
      - "phpunit.xml.dist"
      - "composer.json"
      - "composer.lock"

jobs:
  tests:
    uses: ITinternalDiMartino/ci-workflows/.github/workflows/laravel-packages-run-tests.yml@main
    with:
      php-versions: '["8.3"]'
      laravel-versions: '["12.*", "11.*"]'
      stability: '["prefer-stable"]'
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
